[package]
name = "work"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["core/*"]

[workspace.dependencies]
figment = { version = "0", features = ["env", "toml"] }
serde = { version = "1" }
thiserror = { version = "2" }
anyhow = { version = "1" }
tracing = { version = "0" }
tracing-appender = { version = "0" }
tracing-subscriber = { version = "0", features = [
    "std",
    "fmt",
    "env-filter",
    "tracing-log",
    "time",
    "local-time",
    "json",
] }
time = { version = "0" }
validator = { version = "0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
salvo = { version = "0", features = ["full"] }
sea-orm = { version = "1", "features" = [
    "runtime-tokio-rustls",
    "sqlx-sqlite",
    "sqlx-postgres",
] }
jsonwebtoken = { version = "10" }
rust-embed = { version = "8" }
tera = { version = "1" }
argon2 = { version = "0" }
blake3 = { version = "1" }
rand = { version = "0" }

[dependencies]
mimalloc = { version = "0", default-features = false }
# openssl = { version = "*", features = ["vendored"] }
tokio = { workspace = true }

api = { path = "core/api" }
config = { path = "core/config" }
db = { path = "core/db" }
dto = { path = "core/dto" }
entity = { path = "core/entity" }
hoop = { path = "core/hoop" }
util = { path = "core/util" }
common = { path = "core/common" }


[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3
[profile.release]
codegen-units = 1
debug = false
lto = "fat"
opt-level = 3
panic = "abort"
strip = "symbols"
